import App from './App.uvue'
import mNavigationBar from '@/components/m-navigation-bar/index.uvue'
import { mIcon } from '@/components/m-icon'
import mEmptyDataUvue from '@/components/m-empty-data/m-empty-data.uvue'

import { createSSRApp } from 'vue'

export function createApp() {
	const app = createSSRApp(App)
	app.component('m-navigation-bar', mNavigationBar)
	app.component('m-icon', mIcon)
	app.component('m-empty-data', mEmptyDataUvue)
	return {
		app
	}
}
