/**
 * 判断数组是否为空
 */
export const isEmpty = (arr: Array | null):Boolean =>{
	if(arr!=null) {
		return arr.length == 0;
	}
	return true;
}
/**
 * 判断数组是否不为为空
 */
export const isNotEmpty = (arr: Array | null):Boolean =>{
	return !isEmpty(arr)
}
/**
 * 获取数组长度
 */
export const length = (arr: Array | null):number => {
	if(arr!=null) {
		return arr.length;
	}
	return 0;
}
type CollUtilType = {
	isEmpty: (arr: Array | null) => boolean;
	isNotEmpty: (arr: Array | null) => boolean;
	length: (arr: Array | null) => number;
}
export const $collUtil: CollUtilType = {
	isEmpty,
	isNotEmpty,
	length
}